## API KEY
GOOGLE_API_KEY: AIzaSyCdTM1EFBW8XqglETtgQnVclmesPGOhi0Q

NEO4J_URI: "neo4j+ssc://7f69e5c5.databases.neo4j.io"
NEO4J_USERNAME: "neo4j"
NEO4J_PASSWORD: "AqY8r2duR2NIvkD_Zdwm6BSblbcNN_K2i8wwfECMA38"